'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HERBS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dice_blue_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dice_blue_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dice_blue_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dice_blue_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dice_red_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dice_red_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dice_red_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dice_red_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ForestBackDrop_Controls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForestBackDrop_Controls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ForestPathVol6Public() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForestPathVol6Public", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HERBS_Cauldron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HERBS_Cauldron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;library&gt;
        '''  &lt;type&gt;Painkiller,Replenisher,Healer,Vigour,Defender&lt;/type&gt;
        '''  &lt;level&gt;Low,Medium,High,Very High&lt;/level&gt;
        '''  &lt;steps&gt;
        '''    &lt;potency&gt;Low&lt;/potency&gt;
        '''    &lt;formula&gt;Low|4,Medium|12,High|36&lt;/formula&gt;
        '''  &lt;/steps&gt;
        '''
        '''  &lt;steps&gt;
        '''    &lt;potency&gt;Medium&lt;/potency&gt;
        '''    &lt;formula&gt;Low|2,Medium|4,High|12,Very High|36&lt;/formula&gt;
        '''  &lt;/steps&gt;
        '''
        '''  &lt;steps&gt;
        '''    &lt;potency&gt;High&lt;/potency&gt;
        '''    &lt;formula&gt;Medium|2,High|4,Very High|12&lt;/formula&gt;
        '''  &lt;/steps&gt;
        '''  
        '''  &lt;steps&gt;
        '''    &lt;potency&gt;Very [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Herbs_library() As String
            Get
                Return ResourceManager.GetString("Herbs_library", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Map_Blank_A_2x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Map_Blank_A_2x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;library&gt;
        '''  &lt;stacksize&gt;10&lt;/stacksize&gt;
        '''  &lt;medicines&gt;
        '''    &lt;type&gt;Painkiller&lt;/type&gt;
        '''    &lt;info&gt;While under the effects of a Painkiller, you suffer no penalties from disease or lingering injuriues, and can partially supress exhaustion, additionally when you reach 0 hit points, you do not fall unconscious, you still make death saving throws at the end of your turn, but can keep fighting until you die. However you can choose to go unconscious at any point.^Painkillers ha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Medicine_library() As String
            Get
                Return ResourceManager.GetString("Medicine_library", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mortarpestle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mortarpestle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mortarpestle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mortarpestle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Table_Rectangle_Wood_Ashen_J_2x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Table_Rectangle_Wood_Ashen_J_2x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vial_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vial_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vial_emptygreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vial_emptygreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vialc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vialc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vialc_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vialc_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property woodtabs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodtabs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
